package com.phms.pojo;

import java.util.Date;

public class PetDaily  extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.pet_id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.user_id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.temperature
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Double temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.weight
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.height
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.appetite
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Double appetite;
    private String name;
    private String dateTime;

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.status
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_daily.create_time
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.id
     *
     * @return the value of pet_daily.id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.id
     *
     * @param id the value for pet_daily.id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.pet_id
     *
     * @return the value of pet_daily.pet_id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.pet_id
     *
     * @param petId the value for pet_daily.pet_id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.user_id
     *
     * @return the value of pet_daily.user_id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.user_id
     *
     * @param userId the value for pet_daily.user_id
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.temperature
     *
     * @return the value of pet_daily.temperature
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.temperature
     *
     * @param temperature the value for pet_daily.temperature
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.weight
     *
     * @return the value of pet_daily.weight
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.weight
     *
     * @param weight the value for pet_daily.weight
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.height
     *
     * @return the value of pet_daily.height
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.height
     *
     * @param height the value for pet_daily.height
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.appetite
     *
     * @return the value of pet_daily.appetite
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Double getAppetite() {
        return appetite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.appetite
     *
     * @param appetite the value for pet_daily.appetite
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setAppetite(Double appetite) {
        this.appetite = appetite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.status
     *
     * @return the value of pet_daily.status
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.status
     *
     * @param status the value for pet_daily.status
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_daily.create_time
     *
     * @return the value of pet_daily.create_time
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_daily.create_time
     *
     * @param createTime the value for pet_daily.create_time
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}